### ISSUE TITLE
panic: 微信返回的数据有误

### ISSUE THREAD

**Issue by ChinaArJun** [Han-Ya-Jun/news_watch_notice#1]
{
"BaseResponse": {
"Ret": 1,
"ErrMsg": ""
}
,
"Count": 0,
"ContactList": [],
"SyncKey": {
"Count": 0,
"List": []
}
,
"User": {
"Uin": 0,
"UserName": "",
"NickName": "",
"HeadImgUrl": "",
"RemarkName": "",
"PYInitial": "",
"PYQuanPin": "",
"RemarkPYInitial": "",
"RemarkPYQuanPin": "",
"HideInputBarFlag": 0,
"StarFriend": 0,
"Sex": 0,
"Signature": "",
"AppAccountFlag": 0,
"VerifyFlag": 0,
"ContactFlag": 0,
"WebWxPluginSwitch": 0,
"HeadImgFlag": 0,
"SnsFlag": 0
}
,
"ChatSet": "",
"SKey": "",
"ClientVersion": 0,
"SystemTime": 0,
"GrayScale": 0,
"InviteStartCount": 0,
"MPSubscribeMsgCount": 0,
"MPSubscribeMsgList": [],
"ClickReportInterval": 0
}

panic: 微信返回的数据有误

goroutine 1 [running]:
news_watch_notice/utils.PanicErr(...)
	/go/cache/utils/common_utils.go:33
news_watch_notice/pkg/wechat.WechatLogin(0xb0c662, 0xb, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/cache/pkg/wechat/wechat.go:70 +0x856
main.main()
	/go/cache/cmd/news_watch_notice.go:53 +0x1d69

**Comment by Han-Ya-Jun** [comment]
那个是用的第三方的微信包，可能是有点问题，不建议用微信推送
